# Generated by Django 5.2.4 on 2025-08-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_order_delivery_name_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_name',
            field=models.CharField(default='Unknown Customer', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash_on_delivery', 'Cash on Delivery'), ('online_payment', 'Online Payment')], default='cash_on_delivery', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='shopkeeper',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
