# Generated by Django 5.2.5 on 2025-08-12 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_alter_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
