# Generated by Django 5.2.7 on 2025-10-23 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_shopkeeper_closed_until_productrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('dairy', 'Dairy & Milk'), ('vegetables', 'Vegetables'), ('fruits', 'Fruits'), ('grains', 'Grains & Cereals'), ('spices', 'Spices & Condiments'), ('beverages', 'Beverages'), ('snacks', 'Snacks'), ('household', 'Household Items'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
